version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: vamana_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: my_node_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MongoURI: mongodb://admin:password@mongodb:27017/mydatabase?authSource=admin

volumes:
  mongo_data:
